# Generated by Django 4.1.1 on 2023-10-12 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='risk',
            field=models.IntegerField(choices=[(8, 'low'), (10, 'medium'), (12, 'high')], default=8),
        ),
    ]
