# Generated by Django 4.1.1 on 2023-10-12 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_userinput_remove_investment_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserInput',
        ),
        migrations.RemoveField(
            model_name='investment',
            name='risk',
        ),
        migrations.AddField(
            model_name='investment',
            name='ideas',
            field=models.TextField(default='Test Ideas'),
            preserve_default=False,
        ),
    ]
