# Generated by Django 4.1.1 on 2023-10-12 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_delete_userinput_remove_investment_risk_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investment',
            name='ideas',
        ),
    ]
