# Generated by Django 4.1.1 on 2023-10-13 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_remove_investment_ideas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Investment1',
            fields=[
                ('investment_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('prize', models.IntegerField()),
                ('total_amount', models.IntegerField(default=0)),
            ],
        ),
    ]
