# Generated by Django 4.1.1 on 2023-10-13 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_investment1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='investment1',
            old_name='investment_id',
            new_name='investment1_id',
        ),
    ]
