# Generated by Django 4.1.1 on 2023-10-13 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_rename_investment_id_investment1_investment1_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Investment1',
            new_name='Investor',
        ),
        migrations.RenameField(
            model_name='investor',
            old_name='investment1_id',
            new_name='investor_id',
        ),
    ]
